### PR TITLE
Extended html output

### PR DESCRIPTION
**Pull request by lu-zero**
And some refactoring to make it more usable.

### CODE REVIEW

**Comment by ligurio** [comment]
Do we have any chance to merge it?

**Comment by davidvanwyk** [comment]
@latk I am aware that you're going to have your hands full trying to handle all these open pull requests, but this will make a world of difference in generating more attractive and modern-looking html outputs.

**Comment by latk** [comment]
This PR has grown far too massive and touches on too many different subjects to ever be merged, and the gcovr master branch has diverged significantly over the years. That is unfortunate because there are many great ideas in here.

So instead, I want to look at this commit by commit to see which ideas can be used independently, without doing an actual merge.

 - :white_check_mark: done:
    aa3b4cc by Luca Barbato: whitespace: Clean up trailing spaces and tabs

 - :alarm_clock: in progres as #234:
    cad1e3e by Luca Barbato: template: Move to jinja2

 - :question: 2a19392 by Luca Barbato: html: Make possible to output to a directory
    Use the path separator to discriminate
    -o name.html  -> filename name.html
    -o dir/ -> filename dir/index.html

 - :question: bc2abd2 by Luca Barbato: html: use Bootstrap

 - :alarm_clock: in progress as #234:
    ff48988 by Luca Barbato: setup: Add jinja2

 - :white_check_mark: done:
    ea0049a by Luca Barbato: gcovr: Split data processing from the script

 - :white_check_mark: done:
    39f0229 by Luca Barbato: gcovr: Split xml reporting

 - :white_check_mark: done:
    530adef by Luca Barbato: gcovr: Split text output

 - :white_check_mark: done:
    37aeea8 by Luca Barbato: gcovr: Split html reporting

 - :white_check_mark: done:
    05d68fa by Luca Barbato: add left over file

 - :question: 412a5d5 by Luca Barbato: html: Update the template

 - :question: b7b1cca by Luca Barbato: html: Fix style a bit

 - :white_check_mark: no longer relevant:
    b29afd5 by Nikolaj Schumacher: Fix wrong argument type.

 - :question: 89ee887 by Luca Barbato: setup: Add dependency

 - :question: 9bce5f3 by Luca Barbato: html: Linkable line numbers

 - :white_check_mark: done:
    695be41 by David Holm: Resolve style errors

    Numerous style errors resolved with disregard for whether the code should be rewritten or not.  One change was made which removes support for Python <2.6 in order to fix the last issue.

    As I think back to the work performed on this file, the thought of opening the next one sends shivers down my spine.

 - :x: a different approach to error messages is proposed in #228:
    7c2e70d by David Holm: Raise an exception on GCOV errors

    If GCOV fails during execution raise the exception GcovError.  It will contain an error message and the filename that was being processed when the error occured.

 - :white_check_mark: done:
    9f500db by David Holm: Resolve style errors

    Fixes the style errors in the gcovr script itself.  Also removes code duplication in the form of a reimplementation of os.walk.

 - :white_check_mark: done:
    bec5311 by David Holm: Resolve remaining style errors

    Fixes the remaining style errors in the gcovr sources.

 - :white_check_mark: done:
    8d6960a by David Holm: Extract function find_gcov_files

    Extracted the function "find_gcov_files" from the massive "process_datafile" function.

 - :x: I don't see the point of this change, but some refactoring has happened in #228:
    4c59c21 by David Holm: Extract function find_potential_wd

    Extracts the function "find_potential_wd" from the (now less) massive function
    "process_datafile".

 - :question: f085abe by David Holm: Extract class Gcov
    Move all functionality related to gcov execution into the class "Gcov".  The function "process_datafile" is now starting to look decent.

 - :question: has been partially implemented in #228, but contains some interesting ideas:
    e1db60b by David Holm: Extract class from process_gcov_data
    Extracted class "GcovParser" from GCOV parser code.  Redesigned to use re.Scanner which is somewhat nicer than a bunch or if/else statements.  It still needs some work before I would call the parser acceptable.

 - :question: 39ea10d by Luca Barbato: html: Leverage jinja2
    Split head and footer from the pages and start to shape up the layout a little.

 - :question: ec17299 by David Holm: Extract functions for checking if a file is gcda/gcno

 - :question: 2ed8d3f by David Holm: Support for cross-profiling
    When cross-profiling with GCOV the data files are stored in a different directory than the source code.  When a user specifies a --gcov-prefix in the call to gcovr it must create symbolic links in the correct place or GCOV will not be able to parse the data [1].

     [1]: http://gcc.gnu.org/onlinedocs/gcc/Cross-profiling.html

From the inappliccable changes, good ideas:

 - :bulb: do not emit warnings or errors outside of the main, perhaps use exceptions instead

I would welcome discussions, issues, and pull requests about the open points.

**Comment by Spacetown** [comment]
@latk I think all issues are done and we can close this PR.

**Comment by Spacetown** [comment]
All issues are done.

**Pull request closed without merging**
