### PR TITLE
Detect suspicious counters

### LINKED ISSUE #898: Abnormal high line coverage on a function
**Describe the bug**
For unknown reasons, there is a part of coverage report than is not working properly on one of my functions.

The line coverage results in 1095216660480 (255 * 2^32) on just a few lines, even if the function is not called.

I am unsure if this is related, but the following warning also occurs during the gcovr call:
```
(WARNING) Ignoring negative hits in line 'branch  1 taken -1095216660478'.
```

I do not use any jump instructions. It is just if/else condition within a function.

Moving the function definition to another position in the same file seems to solve the problem for now.

**To Reproduce**
I sadly do not know how to reproduce this issue. The code is not shareable, and I do not manage to reproduce it in a dummy project yet. I will update this issue if I manage to setup an minimum code example.

**Expected behavior**
The code coverage should be similar to the second screenshot. The second part of the branch coverage is affected by the error.

**Screenshots**
Issue:
image

After moving the code to another place in the same source file:
image

**Desktop:**
 - OS: ubuntu 22.04
 - GCC version 11.4
 - GCOVR version 6.0

### PR DESCRIPTION
**Pull request by Spacetown**
A suspicious counter is a counter value of 2^32 or greater.

@JohanBertrand Please can you check this branch with your code?

Closes #898

### CODE REVIEW

**Comment by JohanBertrand** [comment]
I just tested with the flag: `--gcov-ignore-parse-errors=all`

Here is the result:
```
(INFO) Reading coverage data...
(WARNING) Unrecognized GCOV output for myfile.c
          1095216660480:  648:        my_variable =  something;
          1095216660480:  649:        my_variable =  something;
          1095216660480:  650:        my_function(
          1095216660480:  652:            my_variable);
          1095216660480:  652-block  0
          call    0 returned 0
        This is indicative of a gcov output parse error.
        Please report this to the gcovr developers
        at <https://github.com/gcovr/gcovr/issues>.
(WARNING) Exception during parsing:
        SuspiciousHits: Got suspicious hit value in gcov line '1095216660480:  648:        my_variable =  something;' caused by a bug in gcov tool, see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=68080. Use option --gcov-ignore-parse-errors with a value of suspicious_hits.warn, or suspicious_hits.warn_once_per_file.
(WARNING) Exception during parsing:
        SuspiciousHits: Got suspicious hit value in gcov line '1095216660480:  649:        my_variable =  something;' caused by a bug in gcov tool, see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=68080. Use option --gcov-ignore-parse-errors with a value of suspicious_hits.warn, or suspicious_hits.warn_once_per_file.
(WARNING) Exception during parsing:
        SuspiciousHits: Got suspicious hit value in gcov line '1095216660480:  650:        my_function(' caused by a bug in gcov tool, see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=68080. Use option --gcov-ignore-parse-errors with a value of suspicious_hits.warn, or suspicious_hits.warn_once_per_file.
(WARNING) Exception during parsing:
        SuspiciousHits: Got suspicious hit value in gcov line '1095216660480:  652:            my_variable);' caused by a bug in gcov tool, see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=68080. Use option --gcov-ignore-parse-errors with a value of suspicious_hits.warn, or suspicious_hits.warn_once_per_file.
(WARNING) Exception during parsing:
        SuspiciousHits: Got suspicious hit value in gcov line '1095216660480:  652-block  0' caused by a bug in gcov tool, see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=68080. Use option --gcov-ignore-parse-errors with a value of suspicious_hits.warn, or suspicious_hits.warn_once_per_file.
(WARNING) Exception during parsing:
        KeyError: 651
(INFO) Writing coverage report...
```

Is it normal that it is not warning me about the negative values anymore here? 
I checked the result of gcov, and it's still there.
I have high values, negatives and positives on line counts, and negative on branches, like mentioned on the issue.

**Comment by Spacetown** [comment]
The option value `all` from `--gcov-ignore-parse-errors=all` was not used in the logic to skip this error (same for negative hits). I've fixed this, please try again.

**Comment by JohanBertrand** [comment]
It seems like something is wrong now, I do not see all the errors anymore, and the warnings are displayed twice (First in white, and then in yellow. I'm still using `--gcov-ignore-parse-errors=all`

Here is the new output:

```
(INFO) Reading coverage data...
WARNING:gcovr:Ignoring suspicious hits in line '1095216660480:  648:        my_variable =  something;'.
(WARNING) Ignoring suspicious hits in line '1095216660480:  648:        my_variable =  something;'.
WARNING:gcovr:Ignored 5 issues overall.
(WARNING) Ignored 5 issues overall.
INFO:gcovr:Writing coverage report...
(INFO) Writing coverage report...
```

**Comment by Spacetown** [comment]
The logger issue was fixed on main.
By ignoring the errors they are converted to warnings. The missing messages where the result of an error in the logic of handling `--gcov-ignore-parse-errors=suspicious_hits.warn` and `--gcov-ignore-parse-errors=suspicious_hits.warn_once_per_file`. I've fixed this and extended the tests. If you ignore all errors you should see all of your messages but it's better to ignore only the specific errors to get informed if another error occurs.

**Comment by JohanBertrand** [comment]
Alright, here is now the output with `--gcov-ignore-parse-errors=all`:

```
(INFO) Reading coverage data...
(WARNING) Ignoring suspicious hits in line 'branch  0 taken 1095216668677 (fallthrough)'.
(WARNING) Ignoring negative hits in line 'branch  1 taken -1095216652247'.
(WARNING) Ignoring suspicious hits in line '1095216668677:  625:        my_variable =  something;'.
(WARNING) Ignoring suspicious hits in line '1095216668677:  626:        my_variable =  something;'.
(WARNING) Ignoring suspicious hits in line '1095216668677:  627:        my_function('.
(WARNING) Ignoring suspicious hits in line '1095216668677:  629:            my_variable);'.
(WARNING) Ignoring suspicious hits in line '1095216668677:  629-block  0'.
(INFO) Writing coverage report...
```

I feel like something is missing to identify where the warnings are with the branches because it does not show where it is located. Also, it might be nice to be able to see the file that is concerned by those warnings.

Otherwise, that's looking pretty nice, thank you!

**Comment by Spacetown** [comment]
In python we don't have a limit. The limit is in gcov. I do not think that you hit a line 4.294.967.296 in one test.

**Pull request merged**
