### PR TITLE
Change Version numbers to strings

### PR DESCRIPTION
**Pull request by Jugst3r**
Quick fix, tests should be clean

### CODE REVIEW

**Review by latk — APPROVED** [review]
Fantastic, thanks! For completeness sake, could you also add your name or alias to the AUTHORS file?

**Comment by Spacetown** [comment]
@latk I'm wondering about the coverage report. There are files listed which are not changed in this PR (Last update 73e8776...2645888.). Commit 73e8776 is #405 which is 8 days old.

**Comment by latk** [comment]
@Spacetown Yeah, Codecov produces really weird/misleading summaries. Apparently it doesn't compare coverage state with the master branch but with the parent commit. The first commit of this PR is 4cf2b91a3741ac13b4be3f5c13e1816e03f22f2e, the parent of which is indeed 73e8776.

**Comment by Spacetown** [comment]
@latk  Ok. I thought this is because I did something wrong when switching to GitHub.

**Review by Spacetown — APPROVED** [review]
LGFM

**Pull request merged**
