### PR TITLE
Add option to change threshold in HTML

### PR DESCRIPTION
**Pull request by Spacetown**
#261 
Also an option to change the title is added.

### CODE REVIEW

**Comment by Spacetown** [comment]
I have problems because the pull request was on branch master and now I cannot sync the repos. I close the request and try to delete the fork.

**Comment by latk** [comment]
stop! that's not necessary

**Comment by latk** [comment]
To recover from this:

 - `git fetch --all` the remote repositories. If your fork is origin and this repo is upstream, then the upstream head will be in the branch `upstream/master`.
 - you can now merge or rebase your changes on the upstream/master.
 - once you have everything resolved locally, you can force-push your changes. You see many people advise against this, but this depends on context: for your personal branches and for pull requests, it's ok to force-push. You would typically use `git push --force-with-lease`.

If you're having problems with git, it's easier for me to help you via chat than via this issue tracker. E.g. there's a [Gitter chatroom](https://gitter.im/gcovr/gcovr). If necessary you can also contact me via email (see the git log).

**Comment by Spacetown** [comment]
Sorry, already done. :-(

**Pull request closed without merging**
