### PR TITLE
Upload coverage data from GitHub actions.

### PR DESCRIPTION
**Pull request by Spacetown**
@latk Can we now remove appveyor tests? GCC5 is checked in Docker and Windows is checked with GCC-8.

### CODE REVIEW

**Comment by Spacetown** [comment]
Differences in coverage are because the report is know generated under ubuntu.

**Comment by latk** [comment]
Would it be possible to collect coverage in one Windows build as well? Codecov merges multiple uploaded reports, which is helpful because we have some Windows- and some Linux-specific tests.

I'll delete Appveyor ass soon as you say so, or when this PR is merged.

**Review by latk — APPROVED** [review]
Looks good!

I think the Appveyor config can be deleted as well.

**Comment by Spacetown** [comment]
@latk It seems that with the GitHub actions the data is visible as comment but the test is missing. I'll try to call the commen `codecov -X gcov search` used in appveyor to upload the data. Codecov.io support user defined flags for the upload, I'll try to flag with the OS.

**Comment by Spacetown** [comment]
@latk The requred appveyor test can be removed.

**Comment by latk** [comment]
ok done, Appveyor is deleted. Thank you very much for making this possible!

**Comment by Spacetown** [comment]
And what about the missing needed test? Was there a special configuration on appveyor?

**Comment by latk** [comment]
I think the codecov website is just unreliable in the diff view, but is actually processing the correct data. So I don't think anything has to be fixed regarding coverage collection (at least on our part).

**Comment by Spacetown** [comment]
Strange, now the codecov is listed again. ???
Maybe this was an issue with the required appveyor test.

**Pull request merged**
