### PR TITLE
Great documentation overhaul: rst user guide, release simplifications

### PR DESCRIPTION
**Pull request by latk**
In this PR, a number of changes were made to the documentation system, in particular the User Guide.

The guide was translated from AsciiDoc to ReStructured Text (rst). This allows us to more easily include separate files. E.g. example code can be included without the `include_anchors.py` script. The installation instructions and abstract are taken from the README. The list of contributors is taken directly from the AUTHORS file.

Long term, this change will also allow us to manage the documentation with Sphinx.

The drawback of this approach is that the guide.rst is unreadable on GitHub, because the `.. include::` directive is disabled for security reasons. The guide can still be read on the website.

The guide has gained a new section about using filters. How filters behave is one of the more confusing parts of gcovr (see #178). The guide also includes warnings about how Windows filters are expected to change (see #191).

This PR includes a number of related changes:

 - The examples were renamed and simplified. Instead of `example2.sh` we now have `example_xml.sh`. This makes the examples less confusing, at least for me.

 - The guide is no longer rendered as EPUB and PDF. I'm open to reinstating this for a future release, but right now these extra output formats complicate the release process. This also allows us to throw out the included dbtoepub Ruby script (`doc/epub/*`).

 - As AsciiDoc is no longer used, the icon set (`doc/images/*`) could be removed.

 - Screen shots can (optionally) be made automatically by wkhtmltopdf.

This PR solves the last blockers for the next release (see #202). The next step would be to bump the version and trigger a deployment.

### CODE REVIEW

**Comment by whart222** [comment]
Moving away from AsciiDoc to Restructured Text is a great idea.  Is the plan to generate documentation with ReadTheDocs?  I've used that strategy on other projects, and I've been happy with the results.

**Comment by latk** [comment]
Thank you @whart222! I hope it's OK that I'm changing so much stuff around.

ReadTheDocs will definitively be the simplest way to host & build the
documentation. But I have never done that before, so if you can provide any
help that would be great :) Some way along the road, I would need your
assistance to point the gcovr.com domain at RTD.

Right now my priority is getting this release out of the door, then working
on the modularization. Moving to Sphinx and RTD is not at the top of my
list, but it would definitively be an improvement. E.g. there's a Sphinx
plugin to display the command line options in a more readable format.


2018-02-07 20:48 GMT+01:00 William Hart <notifications@github.com>:

**Comment by whart222** [comment]
Yep.  I've been enjoying all of the energy that you've brought to gcovr
development.  :) :)

**Comment by whart222** [comment]
Let me see if I can setup RTD.  I already have an account, so this might be
super easy for me.

**Comment by mayeut** [comment]
Nice job. Moving to Sphinx & RTD would definitively be an improvement. This is a first step toward that.

**Pull request merged**
