### PR TITLE
Fix type error in decision analysis

### PR DESCRIPTION
**Pull request by genossefloyd**
Proposal for fix of #783 
Avoiding TypeError exception if `self.coverage.lines` is empty during decision analysis

### CODE REVIEW

**Comment by Spacetown** [comment]
Thank you for fixing this. Can you also extend the decision test to raise this exception without your fix?

**Comment by genossefloyd** [comment]
I have extended the decisions test with a setup using a second cpp, that was raising the issue - but only for clang (14) and not for gcc (10).

The two failing test cases require an update of the json and html output reference. The "--update-reference" command did not work for me... I also do not have all the required build environments. Could you straigthen out these references yourself?

**Comment by Spacetown** [comment]
> The "--update-reference" command did not work for me...

The switch is written with a `_`and not a `-` in the middle.

The change in the makefile is not working for us. Can you modify the test to use a enumeration in the same C-File without adding another compile unit?
I guess the problem is the scope operator in the case value.

**Comment by genossefloyd** [comment]
I tried to different switch-variations (with break, return, additional brackets, ...) to make it come up with one cpp but it does not work. There have to be two cpp's.

As far as I understood it, the code in one cpp is creating some actual coverage of the switch statement, the other one only references the containing class but does not call the relevant function, so it ends up with 0 coverage and we end up with an empty list.

I have no real insights on how gcov works exactly but that is my best guess about whats happening after trying several setups half of the day.

As I am a bit out of time/resources to investigate the problem any further, I can not continue working on it - at least for the next couple of weeks. Sorry about that.

**Review by Spacetown — CHANGES_REQUESTED** [review]

**Pull request merged**
