### PR TITLE
pygments required >= 2.13.0

### PR DESCRIPTION
**Pull request by mfont-bz17**
* Fix pygments version 2.13.0 in tests enviroment
    * Update reference of tests using new pygments version

Related to #793

### CODE REVIEW

**Comment by Spacetown** [comment]
You need to update the CHANGELOG.md, the authors will be updated with #793.

**Comment by Spacetown** [comment]
The different files for Windows are attached as Artifacts to the run. You can download them and update your reference data.

**Comment by mfont-bz17** [comment]
> The different files for Windows are attached as Artifacts to the run. You can download them and update your reference data.

I updated the reference data with the artifacts attached but still fails. Is there some way to test the windows parts locally?

**Review by Spacetown — APPROVED** [review]
LGFM

**Pull request merged**
