### PR TITLE
More flexible gcov file parsing

### PR DESCRIPTION
**Pull request by latk**
In #621, it was shown that some third party tools generate `.gcov` files with a slight modification: in lines without coverage, a 6-character `######` marker was used instead of GCC's 5-character marker:

```
 #####:  123: some_code();
```

While gcovr only really supports GCC's gcov and Clang's llvm-cov as coverage data sources, this is a simple fix.

**Question:** should we merge this, or is this unnecessary tech debt?

### CODE REVIEW

**Review by tacooper — APPROVED** [review]
This flexibility seems mostly harmless™ to me, while also allowing compatibility with older versions of 3rd party tools (for example, even if ARM updates their coverage tool, users bound to older versions of the ARM tool can still benefit from the latest gcovr version).

**Comment by Spacetown** [comment]
If the marker is the same and only the length is different it's ok for me. But if a tool introduce different markers I won't add support for them.

For me this would be more clear:
```python
    def _is_marker(count: str, expected_marker: str) -> bool:
        """Recognize markers for uncovered items like ``#####``."""
        if len(count) < 5:
            return false

        unique_chars = set(count)
        if len(unique_chars) > 1:
            return false

        # Also allow if the marker char is repeated more often,
        # see: <https://github.com/gcovr/gcovr/issues/621>
        return expected_marker == unique_chars[0]
```
And using it with the single character of the marker:
```python
_is_marker(count_str, "#")
```

**Comment by latk** [comment]
@Spacetown That's a very good point. I updated the function to the far more clearer:

```python
def _is_marker(count_str: str, marker_char: str) -> bool:
    """Recognize markers for uncovered items like ``#####``."""
    # The GCC gcov marker is exactly 5 chars long,
    # but some tools generate longer markers
    # (see <https://github.com/gcovr/gcovr/issues/621>).
    return len(count_str) >= 5 and all(c == marker_char for c in count_str)
```

**Review by Spacetown — APPROVED** [review]
LGFM.

**Comment by Spacetown** [comment]
@latk Shall we merge this? Pro is that the user of Keil uVision can still use the latest version of `gcov´ without any patch.

**Pull request merged**
