### PR TITLE
Use different color for partial covered lines

### LINKED ISSUE #838: Branch Summary line color based off branches traversed.
I have a small problem with how there is only the percentage and black mono color fractions to visually Identify branch coverage. 

It would be nice to have a color like the yellow or red on the branch line summary to identify the usage of branches.

An alternative could be to change the color of the font for the branch line summary to a different color instead of the line.

### PR DESCRIPTION
**Pull request by Spacetown**
Use a different color in HTML report if not all branches in a line are covered.
In GitHub theme the excluded lines where green which was confusing with the covered lines in green theme.

Closes #838

### CODE REVIEW

**Comment by RatMan64** [comment]
hey @Spacetown, 
I'm a bit of a noob on this repo do I need to pull this branch for testing or just put a comment to say I saw this pr?

**Comment by Spacetown** [comment]
You can directly install my branch with pip as described [here](https://pip.pypa.io/en/stable/getting-started/#install-a-package-from-github)

**Comment by Spacetown** [comment]
You can directly install my branch with pip as described [here](https://pip.pypa.io/en/stable/getting-started/#install-a-package-from-github).

**Comment by Spacetown** [comment]
You can directly install my branch with pip as described [here](https://pip.pypa.io/en/stable/getting-started/#install-a-package-from-github).

**Comment by RatMan64** [comment]
Hey @Spacetown I was able to test this out and looks good however, I did notice some areas of code not getting a definition of coverage. 
```
if (c == '#' || b == '\n' || a == '\0')
{
break;
}
```

**Comment by RatMan64** [comment]
If this is an issue with gcovr and not this feature then Its probably OK.

**Comment by RatMan64** [comment]
Ok this looks like just a general gcovr or my code issue totally separate.

**Comment by Spacetown** [comment]
@RatMan64 Can you add a review comment?

**Review by RatMan64 — COMMENTED** [review]
looks good and works as expected.

**Comment by Spacetown** [comment]
I'll fix this.

**Pull request merged**
